# Pandas That Don’t Just Sit and Chew Bamboo: Advance dataframe manipulation
*No Actual Bears Were Harmed in the Making of This Talk.*

Juan Palomeque-Gonzalez
https://jfpalomeque.com

## Memory efficiency using specific dtypes

In [ ]:
import pandas as pd

# Create a DataFrame from a dictionary with three columns, first column is an integer, second column is a float, and third column is a string. 
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4.3, 5.7, 6.2],
    'C': ['red', 'red', 'blue']
})
df

   A    B     C
0  1  4.3   red
1  2  5.7   red
2  3  6.2  blue

In [23]:
df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      float64
 2   C       3 non-null      object
dtypes: float64(1), int64(1), object(1)
memory usage: 337.0 bytes

In [29]:
from random import randint, random, choice
C = ["red", "blue", "green"]

rows = []
for i in range(1_000_000):
    
    a = randint(1, 100)        
    b = randint(1, 100) + random()  
    c = choice(C)
    
    rows.append([a, b, c])

df = pd.DataFrame(rows, columns=["A", "B", "C"])
df

         A          B      C
0       14  73.869675    red
1       13  39.764137   blue
2       52  82.957451   blue
3       32  30.417805   blue
4       82  66.014157   blue
...     ..        ...    ...
999995  45  20.307383    red
999996  69  28.355352    red
999997  24  86.796402    red
999998  32  73.734624  green
999999  86   8.904186    red

[1000000 rows x 3 columns]

In [31]:
df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 3 columns):
 #   Column  Non-Null Count    Dtype
---  ------  --------------    -----
 0   A       1000000 non-null  int64
 1   B       1000000 non-null  float64
 2   C       1000000 non-null  object
dtypes: float64(1), int64(1), object(1)
memory usage: 65.8 MB

int8: range: -128 to 127
int16: range: -32,768 to 32,767
int32: range: -2,147,483,648 to 2,147,483,647
int64: range: -9,223,372,036,854,775,808 to 9,223,372,036,854,775,807

float16: range: -32,768 to 32,767
float32: range: -1,073,741,824 to 1,073,741,823
float64: range: -9,223,372,036,854,775,808 to 9,223,372,036,854,775,807

In [33]:
df['A'] = df['A'].astype('int8')
df['B'] = df['B'].astype('float16')
df['C'] = df['C'].astype('category')
df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 3 columns):
 #   Column  Non-Null Count    Dtype
---  ------  --------------    -----
 0   A       1000000 non-null  int8
 1   B       1000000 non-null  float16
 2   C       1000000 non-null  category
dtypes: category(1), float16(1), int8(1)
memory usage: 3.8 MB

## Chain functions using pipe

In [46]:
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4.3, 5.7, 6.2],
    'C': ['red', 'red', 'blue']
})
print(df)

   A    B     C
0  1  4.3   red
1  2  5.7   red
2  3  6.2  blue

In [47]:
# Multiply 'A' by 10
df['A'] = df['A'] * 10

# Round 'B'
df['B'] = df['B'].round()

# Filter out rows where 'C' is 'red'
df_filtered = df[df['C'] != 'blue']

print(df_filtered)

    A    B    C
0  10  4.0  red
1  20  6.0  red

In [44]:
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4.3, 5.7, 6.2],
    'C': ['red', 'red', 'blue']
})
# Define our transformation functions
def multiply_A(df):
    df['A'] = df['A'] * 10
    return df

def round_B(df):
    df['B'] = df['B'].round()
    return df

def filter_blue(df):
    return df[df['C'] != 'blue']

# Chain the functions using pipe
df_result = (
    df
    .pipe(multiply_A)
    .pipe(round_B)
    .pipe(filter_blue)
)

print(df_result)

    A    B    C
0  10  4.0  red
1  20  6.0  red

Cleaner code, better readability, modularity and reusability.

## df.query

In [54]:
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4.3, 5.7, 6.2],
    'C': ['red', 'red', 'blue']
})
df

   A    B     C
0  1  4.3   red
1  2  5.7   red
2  3  6.2  blue

In [55]:
filtered_df = df[(df['A'] > 1) & (df['C'] == 'red')]
print(filtered_df)

   A    B    C
1  2  5.7  red

In [56]:
filtered_df_query = df.query('A > 1 & C == "red"')
print(filtered_df_query)

   A    B    C
1  2  5.7  red

## Joining dfs using merge, SQL style

In [63]:
df1 = pd.DataFrame({
    'ID': [1, 2, 3],
    'A': [1, 2, 3],
    'B': [4.3, 5.7, 6.2],
    'C': ['red', 'red', 'blue']
})


df2 = pd.DataFrame({
    'ID': [ 2, 3, 4, 5],
    'D': ['Berry', 'Cherry', 'Orange', 'Banana'],
})

In [64]:
inner_joined = pd.merge(df1, df2, on='ID', how='inner')
print("Inner Join Result:")
print(inner_joined)

Inner Join Result:
   ID  A    B     C       D
0   2  2  5.7   red   Berry
1   3  3  6.2  blue  Cherry

In [65]:
outer_joined = pd.merge(df1, df2, on='ID', how='outer')
print("Outer Join Result:")
print(outer_joined)

Outer Join Result:
   ID    A    B     C       D
0   1  1.0  4.3   red     NaN
1   2  2.0  5.7   red   Berry
2   3  3.0  6.2  blue  Cherry
3   4  NaN  NaN   NaN  Orange
4   5  NaN  NaN   NaN  Banana

##  MultiIndex

In [68]:
df = pd.DataFrame({
    'Store': ['Store A', 'Store A', 'Store A', 'Store B', 'Store B', 'Store B'],
    'Department': ['Electronics', 'Clothing', 'Grocery', 'Electronics', 'Clothing', 'Grocery'],
    'Sales': [20000, 15000, 30000, 25000, 12000, 28000],
    'Profit': [5000, 3000, 7000, 6000, 2500, 6500]
})

# Create a MultiIndex by setting 'Store' and 'Department' as the index
df_multi = df.set_index(['Store', 'Department'])
print(df_multi)

                     Sales  Profit
Store   Department
Store A Electronics  20000    5000
        Clothing     15000    3000
        Grocery      30000    7000
Store B Electronics  25000    6000
        Clothing     12000    2500
        Grocery      28000    6500

In [69]:
clothing_data = df_multi.xs('Store A', level='Store')
print(clothing_data)

             Sales  Profit
Department
Electronics  20000    5000
Clothing     15000    3000
Grocery      30000    7000

In [70]:
clothing_data = df_multi.xs('Clothing', level='Department')
print(clothing_data)

         Sales  Profit
Store
Store A  15000    3000
Store B  12000    2500

In [71]:
store_b_clothing = df_multi.loc[('Store B', 'Clothing')]
print(store_b_clothing)

Sales     12000
Profit     2500
Name: (Store B, Clothing), dtype: int64

In [72]:
total_sales_by_store = df_multi['Sales'].groupby(level='Store').sum()
print(total_sales_by_store)

Store
Store A    65000
Store B    65000
Name: Sales, dtype: int64

In [ ]:
total_sales_by_department = df_multi['Sales'].groupby(level='Department').sum()
print(total_sales_by_department)

Department
Clothing       27000
Electronics    45000
Grocery        58000
Name: Sales, dtype: int64

##  Reshaping

- Long to wide

In [74]:
df = pd.DataFrame({
    'Store': ['Store A', 'Store A', 'Store B', 'Store B', 'Store A', 'Store B'],
    'Department': ['Electronics', 'Clothing', 'Electronics', 'Clothing', 'Electronics', 'Clothing'],
    'Month': ['Jan', 'Jan', 'Jan', 'Jan', 'Feb', 'Feb'],
    'Sales': [20000, 15000, 25000, 12000, 21000, 13000]
})

print("Original DataFrame:")
print(df)

Original DataFrame:
     Store   Department Month  Sales
0  Store A  Electronics   Jan  20000
1  Store A     Clothing   Jan  15000
2  Store B  Electronics   Jan  25000
3  Store B     Clothing   Jan  12000
4  Store A  Electronics   Feb  21000
5  Store B     Clothing   Feb  13000

In [75]:
df_pivot = df.pivot(index=['Store', 'Month'], columns='Department', values='Sales')
print("\nPivoted DataFrame (Wide Format):")
print(df_pivot)

Pivoted DataFrame (Wide Format):
Department     Clothing  Electronics
Store   Month
Store A Feb         NaN      21000.0
        Jan     15000.0      20000.0
Store B Feb     13000.0          NaN
        Jan     12000.0      25000.0

- Wide to long

In [78]:
df_reset = df_pivot.reset_index()

df_melted = pd.melt(df_reset, id_vars=['Store', 'Month'], 
                    var_name='Department', value_name='Sales')

print("\nMelted DataFrame (Long Format):")
print(df_melted)

Melted DataFrame (Long Format):
     Store Month   Department    Sales
0  Store A   Feb     Clothing      NaN
1  Store A   Jan     Clothing  15000.0
2  Store B   Feb     Clothing  13000.0
3  Store B   Jan     Clothing  12000.0
4  Store A   Feb  Electronics  21000.0
5  Store A   Jan  Electronics  20000.0
6  Store B   Feb  Electronics      NaN
7  Store B   Jan  Electronics  25000.0

- Stacking

In [79]:
print(df_pivot)

Department     Clothing  Electronics
Store   Month
Store A Feb         NaN      21000.0
        Jan     15000.0      20000.0
Store B Feb     13000.0          NaN
        Jan     12000.0      25000.0

In [80]:
df_stacked = df_pivot.stack()
print(df_stacked)

Store    Month  Department
Store A  Feb    Electronics    21000.0
         Jan    Clothing       15000.0
                Electronics    20000.0
Store B  Feb    Clothing       13000.0
         Jan    Clothing       12000.0
                Electronics    25000.0
dtype: float64

In [ ]:
df_unstacked = df_stacked.unstack()
print(df_unstacked)

Store              Store A  Store B
Department  Month
Clothing    Feb        NaN  13000.0
            Jan    15000.0  12000.0
Electronics Feb    21000.0      NaN
            Jan    20000.0  25000.0

In [ ]:
df_unstacked = df_stacked.unstack().unstack().unstack().unstack()
print(df_unstacked)

##  Grouping and aggregation

In [89]:
df = pd.DataFrame({
    'Store': ['Store A', 'Store A', 'Store B', 'Store B', 'Store A', 'Store B'],
    'Department': ['Electronics', 'Clothing', 'Electronics', 'Clothing', 'Electronics', 'Grocery'],
    'Sales': [20000, 15000, 25000, 12000, 21000, 13000],
    'Profit': [5000, 3000, 6000, 2500, 7000, 3500]
})

df_multi = df.set_index(['Store', 'Department'])
print(df_multi)

                     Sales  Profit
Store   Department
Store A Electronics  20000    5000
        Clothing     15000    3000
Store B Electronics  25000    6000
        Clothing     12000    2500
Store A Electronics  21000    7000
Store B Grocery      13000    3500

In [90]:
store_group = df_multi.groupby(level='Store').agg({
    'Sales': 'sum',
    'Profit': 'mean'
})
print(store_group)

         Sales  Profit
Store
Store A  56000  5000.0
Store B  50000  4000.0

In [91]:
custom_agg = df_multi.groupby(level='Store').agg({
    'Sales': [
        'sum',                # Total sales
        'mean',               # Average sales
        lambda x: x.max() - x.min()  # Sales range
    ],
    'Profit': [
        'sum',                # Total profit
        'mean',               # Average profit
        lambda x: x.std()     # Profit standard deviation
    ]
})

print(custom_agg)

         Sales                          Profit
           sum          mean <lambda_0>    sum    mean   <lambda_0>
Store
Store A  56000  18666.666667       6000  15000  5000.0  2000.000000
Store B  50000  16666.666667      13000  12000  4000.0  1802.775638

## Window functions

- Moving average

In [92]:
dates = pd.date_range('2025-01-01', periods=10, freq='D')
df = pd.DataFrame({
    'Date': dates,
    'Sales': [200, 220, 250, 270, 260, 300, 320, 310, 330, 340]
})
df.set_index('Date', inplace=True)
print(df)

            Sales
Date
2025-01-01    200
2025-01-02    220
2025-01-03    250
2025-01-04    270
2025-01-05    260
2025-01-06    300
2025-01-07    320
2025-01-08    310
2025-01-09    330
2025-01-10    340

In [93]:
moving_avg_manual = []
sales_values = df['Sales'].tolist()
window_size = 3

for i in range(len(sales_values)):
    if i < window_size - 1:
        moving_avg_manual.append(None)
    else:
        window_sum = sum(sales_values[i-window_size+1:i+1])
        avg = window_sum / window_size
        moving_avg_manual.append(avg)

df['Moving_Avg_Manual'] = moving_avg_manual

print(df)

            Sales  Moving_Avg_Manual
Date
2025-01-01    200                NaN
2025-01-02    220                NaN
2025-01-03    250         223.333333
2025-01-04    270         246.666667
2025-01-05    260         260.000000
2025-01-06    300         276.666667
2025-01-07    320         293.333333
2025-01-08    310         310.000000
2025-01-09    330         320.000000
2025-01-10    340         326.666667

In [94]:
df['Moving_Avg_Window'] = df['Sales'].rolling(window=3).mean()
print(df)

            Sales  Moving_Avg_Manual  Moving_Avg_Window
Date
2025-01-01    200                NaN                NaN
2025-01-02    220                NaN                NaN
2025-01-03    250         223.333333         223.333333
2025-01-04    270         246.666667         246.666667
2025-01-05    260         260.000000         260.000000
2025-01-06    300         276.666667         276.666667
2025-01-07    320         293.333333         293.333333
2025-01-08    310         310.000000         310.000000
2025-01-09    330         320.000000         320.000000
2025-01-10    340         326.666667         326.666667